# Generated by Django 6.0 on 2025-12-26 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(help_text='The kanji character', max_length=1, unique=True)),
                ('meaning', models.TextField(help_text='English meaning(s) of the kanji')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanjiExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(help_text='Japanese text containing the kanji', max_length=100)),
                ('reading', models.CharField(help_text='Reading in hiragana', max_length=200)),
                ('meaning', models.TextField(help_text='English meaning of the example')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='learning.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='KanjiReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(help_text='The reading in hiragana/katakana', max_length=50)),
                ('reading_type', models.CharField(choices=[('onyomi', 'Onyomi (音読み)'), ('kunyomi', 'Kunyomi (訓読み)')], max_length=10)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='learning.kanji')),
            ],
            options={
                'unique_together': {('kanji', 'reading', 'reading_type')},
            },
        ),
        migrations.CreateModel(
            name='KanjiReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField(default=0, help_text='Mastery level (0=learning, higher=mastered)')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.kanji')),
            ],
            options={
                'unique_together': {('kanji',)},
            },
        ),
    ]
