# Generated by Django 6.0 on 2025-12-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanji',
            options={'ordering': ['class_level', 'character']},
        ),
        migrations.AddField(
            model_name='kanji',
            name='class_level',
            field=models.IntegerField(blank=True, help_text='Class/Grade level (1-6) for educational kanji', null=True),
        ),
    ]
